name: 📄 Documentation issue
description: Found an issue in the documentation? You can use this one!
title: "[Docs]:"
labels: ["documentation",'gssoc23','level1']
body:
- type: textarea
  id: description
  attributes:
    label: Current State
  validations:
    required: true
- type: textarea
  id: extra-info
  attributes:
    label: Desired State
  validations:
    required: true    
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: Please add screenshots if applicable
  validations:
    required: false
- type: checkboxes
  id: terms
  attributes:
    label: 'Record'
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
      - label: I'm a GSSoC'23 contributor
      - label: I want to work on this issue
